### ISSUE TITLE
Add the authenticating method using Managed Identity

### ISSUE THREAD

**Issue by turkenf** [crossplane-contrib/provider-upjet-azuread#17]
Adding the authentication method supported by the corresponding provider, see the link below:
- https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/managed_service_identity

**Comment by chatelain-io** [comment]
I would also suggest adding OIDC :

- https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_oidc

**Comment by gravufo** [comment]
I created a PR to implement both managed identities and OIDC methods based on the Azure provider.
Is it possible to get a review and possibly a new release of the provider for this?

Thanks!

**Comment by turkenf** [comment]
Many thanks for your effort @gravufo 🙏  we will take a look next week.
